"""Generate human-readable markdown reports from pipeline outputs."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from .quality import RULES

_HEADER = "<!-- GENERATED by `python -m prism_pipeline.cli` — do not edit by hand. -->\n\n"


def _fmt(v) -> str:
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return "—"
    if isinstance(v, float):
        return f"{v:,.2f}" if not v.is_integer() else f"{int(v):,}"
    return str(v)


def _md_table(df: pd.DataFrame) -> str:
    if df.empty:
        return "_none_\n"
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, r in df.iterrows():
        lines.append("| " + " | ".join(_fmt(r[c]).replace("|", "/") for c in cols) + " |")
    return "\n".join(lines) + "\n"


def write_reconciliation_report(recon: pd.DataFrame, tables: dict, path: Path, manifest: dict) -> None:
    checks = recon[recon["passed"].notna()].copy()
    summary = (
        checks.groupby("month")["passed"].agg(checks="size", passed="sum").reset_index()
        .assign(failed=lambda d: d["checks"] - d["passed"])
    )
    headline = []
    for month, rows in tables["ongoing_long"].groupby("source_month"):
        k = tables["kpis"].set_index("source_month").loc[month]
        headline.append({
            "month": month,
            "projects (official)": k["ongoing_projects"],
            "rows extracted": len(rows),
            "original cost Rs cr (official)": k["original_cost_cr"],
            "sum extracted": round(rows["original_cost_cr"].sum(), 2),
            "expenditure Rs cr (official)": k["expenditure_cr"],
            "sum extracted ": round(rows["cumulative_expenditure_cr"].sum(), 2),
        })
    failures = checks[~checks["passed"].astype(bool)][["check_id", "month", "scope", "expected", "actual", "delta"]]

    text = _HEADER + "# Extraction reconciliation report\n\n"
    text += (
        f"Generated {manifest['generated_at']} · pipeline v{manifest['pipeline_version']}\n\n"
        "Every project row was extracted from Table 6 (\"All Ongoing Projects\") of each official Flash Report. "
        "The sums below are compared with the totals the reports themselves print: the overview page, "
        "Table 1 (ministry-wise, with a grand total), every \"Total (n)\" subtotal inside Table 6, and the "
        "HML sector overview tables. If any row were missing or misread, these would not match.\n\n"
        f"**Result: {manifest['reconciliation']['passed']} of {manifest['reconciliation']['checks']} checks passed.**\n\n"
        "## Headline totals\n\n" + _md_table(pd.DataFrame(headline)) +
        "\n## Checks by month\n\n" + _md_table(summary) +
        "\n## Failed checks\n\n" + _md_table(failures) +
        "\n## Check catalogue\n\n"
        "| ID | What is compared | Tolerance |\n|---|---|---|\n"
        "| R01–R03 | Row count (exact), Σ original cost, Σ expenditure vs overview KPIs | ±1 cr (KPIs are rounded to the crore) |\n"
        "| R04–R06 | Same, vs Table 1 grand total | count exact; sums ±max(0.5, 0.0005 × rows) cr |\n"
        "| R07–R09 | Per ministry: count, Σ original cost, Σ expenditure vs Table 1 | count exact; sums ±max(0.5, 0.0005 × rows) cr |\n"
        "| R10–R12 | Per ministry × sector: vs every 'Total (n)' row in Table 6 | count exact; sums ±max(0.5, 0.0005 × rows) cr |\n"
        "| R13 | Per sector count vs HML 'Sector - Overview' tables | exact |\n"
        "| R14–R16 | Completed / newly-added / NER tables vs overview counts | exact |\n"
        "| R17–R19 | No duplicate codes, no missing code, no missing ministry/sector | exact |\n"
        "\nWhy the sum tolerance scales with row count: Table 1 and the subtotals are computed by the portal "
        "from unrounded source values, while Table 6 prints each row to 2 decimals, so small differences "
        "accumulate over hundreds of rows (largest observed: 0.52 cr over ~2,000 rows). Counts are always "
        "exact, and a single misread value would be orders of magnitude larger.\n"
    )
    path.write_text(text, encoding="utf-8")


def write_quality_report(register: pd.DataFrame, systemic: pd.DataFrame, tables: dict, path: Path,
                         manifest: dict) -> None:
    latest = manifest["latest_month"]
    text = _HEADER + "# Data-quality report\n\n"
    text += (
        f"Generated {manifest['generated_at']} · latest report {latest}\n\n"
        "PRISM **flags** implausible values; it never silently corrects official data. Findings marked "
        "`error` are excluded from model training in Phase 2 and are shown to users with a "
        "\"flagged for verification\" note. Every finding cites the report month and PDF page so it can "
        "be checked by hand.\n\n"
    )

    text += "## Report-wide patterns\n\n" + _md_table(systemic)
    text += (
        "\nReading this table: the latest report prints the revised cost as 0.00 for every project and no "
        "longer carries Legacy OCMS codes or PMG IDs. PRISM therefore carries each project's most recent "
        "reported revised cost forward and labels the month it came from (`revised_cost_asof`).\n\n"
    )

    lifecycle = tables["lifecycle"]
    exits = lifecycle[lifecycle["event"] == "exited"]
    if not exits.empty:
        pivot = exits.pivot_table(index="reason", columns="month", values="project_code", aggfunc="count", fill_value=0)
        pivot["total"] = pivot.sum(axis=1)
        pivot = pivot.reset_index()
        text += (
            "## Why projects leave the ongoing list\n\n"
            "Month-to-month, projects drop out of Table 6. Each exit is classified from evidence in the "
            "reports themselves (completion table, report notes, later re-entry):\n\n" + _md_table(pivot) + "\n"
        )
    notes = tables.get("report_notes")
    if notes is not None and not notes.empty:
        text += "## Official report notes (verbatim)\n\n"
        for month, grp in notes.groupby("source_month"):
            text += f"**{month}**\n\n" + "".join(f"- {n}\n" for n in grp["note"]) + "\n"

    if register.empty:
        text += "No findings.\n"
        path.write_text(text, encoding="utf-8")
        return

    counts = (
        register.groupby(["rule_id", "severity", "title"]).size().rename("findings").reset_index()
        .sort_values("rule_id")
    )
    latest_counts = register[register["source_month"] == latest].groupby("rule_id").size()
    counts["in latest month"] = counts["rule_id"].map(latest_counts).fillna(0).astype(int)
    text += "## Findings by rule\n\n" + _md_table(counts)

    text += "\n## Rule catalogue\n\n| ID | Severity | Rule |\n|---|---|---|\n"
    for r in RULES.values():
        text += f"| {r.rule_id} | {r.severity} | {r.description} |\n"

    cols = ["project_code", "project_name", "ministry", "detail", "source_month", "source_page"]
    for rule_id in sorted(register["rule_id"].unique()):
        sub = register[register["rule_id"] == rule_id]
        rule = RULES[rule_id]
        shown = sub[cols].head(25).copy()
        shown["project_name"] = shown["project_name"].map(lambda s: (s[:70] + "…") if isinstance(s, str) and len(s) > 70 else s)
        text += f"\n## {rule_id} — {rule.title} ({rule.severity}, {len(sub)} findings)\n\n"
        text += _md_table(shown)
        if len(sub) > 25:
            text += f"\n_{len(sub) - 25} more in `pipeline/data/processed/data_quality_register.csv`._\n"
    path.write_text(text, encoding="utf-8")
